---
title: "Konstantin Böhm"
format:
  html:
    toc: true
    toc-depth: 4
    theme:
      light: [flatly, styles/light.scss]
      dark: [darkly, styles/dark.scss]
  pdf:
    pdf-engine: weasyprint
css: styles/cv.css
format-links: [pdf]
embed-resources: true
---

::: {.content-visible when-profile="english"}

::: {.print-only style="text-align: center; font-size: 14pt; font-weight: bold;"}
[Mail](mailto:koni.boehm@gmail.com) | 
[LinkedIn](https://www.linkedin.com/in/konstantindb/) | 
[GitHub](https://github.com/konstantindab)
:::

::: {.print-only style="text-align: center"}
MSc Brain Sciences graduate with a First Class Honours degree in Psychology. Skilled in quantitative and qualitative data analysis. Experienced in clinical and academic research. Strong communication skills and interested in connecting scientific evidence with real-world applications.
:::

## Education
::: {.print-only}
***
:::

**MSc Brain Sciences**[09/2024 --- 09/2025]{.cvdate}  
*University of Glasgow* 

**BSc (Hons) Psychology, First Class Honours**[09/2020 --- 07/2024]{.cvdate}  
*Queen Margaret University, Edinburgh* 

**Abitur (German Secondary Education)**[09/2010 --- 07/2018]{.cvdate}  
*Helene-Lange-Gymnasium Fürth* 

## Research Experience
::: {.print-only}
***
:::

**MSc Dissertation**[*04/2025 --- 08/2025*]{.cvdate}  
*Longitudinal Tracking of Retrosplenial Cortex Neurons During Contextual Fear Retrieval  
in APP^NL-G-F^ Mice Treated with ENT-A061* 

**Student Researcher -- Toy Box Diversity Lab**[*09/2023 --- 07/2024*]{.cvdate}  
*Queen Margaret University, Edinburgh* 

**BSc Dissertation**[*10/2023 --- 04/2024*]{.cvdate}  
*The Power of Purposeful Thinking: Object Function and its Mnemonic Consequences* 

**Research Assistant -- Careena Center for Health**[*07/2023 --- 08/2023*]{.cvdate}  
*Gaborone, Botswana* 

## Skills
::: {.print-only}
***
:::

:::{.container}
:::{.column}
### Technical Skills:  
- Data cleaning and visualisation  
- Statistical modelling  
- High-performance computing  
- Machine learning tools  
- Qualitative analysis  
- R and SPSS/JASP (Advanced)  
- Python and Excel (Intermediate)  
- MATLAB, HTML and CSS (Beginner)  

### Skills and Strengths:  
- Critical thinking  
- Communication  
- Time management
- Intercultural skills  
- Adaptability  
:::

:::{.column}
### Languages:  
- English (Bilingual)  
- German (Native)  
- French (B1+)  
:::
:::  


:::{.page-break}
:::
## Volunteering
::: {.print-only}
***
:::

**Co-founder and Vice President**[*03/2023 --- 05/2024*]{.cvdate}  
*Queen Margaret University, Edinburgh* 

**German Voluntary Service “weltwärts” -- Eine Welt Netz NRW**[*08/2018 --- 08/2019*]{.cvdate}  
*Volunteer at Stepping Stones International in Mochudi, Botswana* 

**Taekwon-Do Coach (Children & Adults)**[*01/2016 --- 09/2020*]{.cvdate}  
*Taekwon-Do Vach* 

**Volunteer -- Congregation of St. Matthews Church**[*10/2015 --- 02/2016*]{.cvdate}  
*Fürth/Vach* 


### Achievements  

Best Newcomer Award  
QMU Running & Cycling  

School Award for Exceptional Engagement  


### Certifications  

PIL (ABC) Training Certificate  
Laboratory Animal Procedures (ASPA)  

Full clean EU driving license  

### Extracurricular Interests  

Taekwon-Do  
Cycling and running  
Saxophone  
  

## Employment History
::: {.print-only}
***
:::

**Games Master**[*01/2023 --- 02/2025*]{.cvdate}  
*Escape Reality Ltd., Scotland* 

**Events Usher -- Open Days**[*09/2021 --- 10/2023*]{.cvdate}  
*Queen Margaret University, Edinburgh* 

**Games Master and Social Media Manager**[*11/2021 --- 11/2022*]{.cvdate}  
*Padlox Escape Rooms, Edinburgh* 

**Administrative Assistant**[*06/2021 --- 08/2021*]{.cvdate}  
*Covid-19 Vaccination Centre -- Arbeitsgemeinschaft Notfallmedizin Fürth e. V.* 

**Logistics Assistant**[*07/2020 --- 09/2020*]{.cvdate}  
*IKEA Germany, Fürth* 

**Kitchen Porter -- Michelin-star Restaurant**[*03/2020 --- 04/2020*]{.cvdate}  
*„L’impertinent“ Biarritz, France* -- Returned to Germany due to Covid-19 

**Retail Assistant**[*05/2017 --- 09/2017*]{.cvdate}  
*E-Center EDEKA Schuler, Fürth* 

**Intern at Radio station -- “Hit Radio N1”**[*07/2015*]{.cvdate}  
*Funkhaus Nürnberg*  


::: {.print-only style="margin-top: 2em;"}
  
**References**  
Available upon request.
:::



::: {.content-visible when-profile="german"}

::: {.print-only style="text-align: center; font-size: 14pt; font-weight: bold;"}
[Mail](mailto:koni.boehm@gmail.com) | 
[LinkedIn](https://www.linkedin.com/in/konstantindb/) | 
[GitHub](https://github.com/konstantindab)
:::

::: {.print-only style="text-align: center"}
MSc Brain Sciences Absolvent mit einem Bachelorabschluss in Psychologie (First-Class Honours). Versiert in quantitativer und qualitativer Datenanalyse. Erfahren in klinischer und akademischer Forschung. Starke Kommunikationsfähigkeiten und Interesse daran, wissenschaftliche Erkenntnisse mit praktischen Anwendungen zu verbinden.
:::

## Ausbildung
::: {.print-only}
***
:::

**MSc Brain Sciences**[09/2024 --- 09/2025]{.cvdate}  
*University of Glasgow* 

**BSc (Hons) Psychologie, First-Class Honours**[09/2020 --- 07/2024]{.cvdate}  
*Queen Margaret University, Edinburgh* 

**Abitur (Allgemeine Hochschulreife)**[09/2010 --- 07/2018]{.cvdate}  
*Helene-Lange-Gymnasium Fürth* 

## Forschungserfahrung
::: {.print-only}
***
:::

**MSc Dissertation**[*04/2025 --- 08/2025*]{.cvdate}  
*Longitudinal Tracking of Retrosplenial Cortex Neurons During Contextual Fear Retrieval  
in APP^NL-G-F^ Mice Treated with ENT-A061* 

**Studentische Hilfskraft -- Toy Box Diversity Lab**[*09/2023 --- 07/2024*]{.cvdate}  
*Queen Margaret University, Edinburgh* 

**BSc Dissertation**[*10/2023 --- 04/2024*]{.cvdate}  
*The Power of Purposeful Thinking: Object Function and its Mnemonic Consequences* 

**Wissenschaftliche Hilfskraft -- Careena Center for Health**[*07/2023 --- 08/2023*]{.cvdate}  
*Gaborone, Botswana* 

## Fähigkeiten
::: {.print-only}
***
:::

:::{.container}
:::{.column}
### Technische Fähigkeiten:  
- Datenbereinigung und Visualisierung  
- Statistische Modellierung  
- Hochleistungsrechnen  
- Tools für maschinelles Lernen  
- Qualitative Analyse  
- R und SPSS/JASP (Fortgeschritten)  
- Python und Excel (Mittelstufe)  
- MATLAB, HTML und CSS (Einsteiger)  

### Kompetenzen und Stärken:  
- Kritisches Denken  
- Kommunikation  
- Zeitmanagement  
- Interkulturelle Kompetenz  
- Anpassungsfähigkeit  
:::

:::{.column}
### Sprachen:  
- Englisch (Bilingual)  
- Deutsch (Muttersprache)  
- Französisch (B1+)  
:::
:::  


:::{.page-break}
:::
## Ehrenamt
::: {.print-only}
***
:::

**Mitbegründer und Vizepräsident**[*03/2023 --- 05/2024*]{.cvdate}  
*Queen Margaret University, Edinburgh* 

**Freiwilligendienst „weltwärts“ -- Eine Welt Netz NRW**[*08/2018 --- 08/2019*]{.cvdate}  
*Freiwilliger bei Stepping Stones International in Mochudi, Botswana* 

**Taekwon-Do Trainer (Kinder & Erwachsene)**[*01/2016 --- 09/2020*]{.cvdate}  
*Taekwon-Do Vach* 

**Freiwilliger -- Kirchengemeinde St. Matthäus**[*10/2015 --- 02/2016*]{.cvdate}  
*Fürth/Vach* 


### Auszeichnungen  

Best Newcomer Award  
QMU Running & Cycling  

Schulpreis für außergewöhnliches Engagement  


### Zertifikate  

PIL (ABC) Trainingszertifikat  
Laboratory Animal Procedures (ASPA)  

EU-Führerschein (unbeschränkt, sauber)  

### Außerschulische Interessen  

Taekwon-Do  
Radfahren und Laufen  
Saxophon  
  

## Berufserfahrung
::: {.print-only}
***
:::

**Games Master**[*01/2023 --- 02/2025*]{.cvdate}  
*Escape Reality Ltd., Schottland* 

**Eventhelfer -- Informationstage**[*09/2021 --- 10/2023*]{.cvdate}  
*Queen Margaret University, Edinburgh* 

**Games Master und Social Media Manager**[*11/2021 --- 11/2022*]{.cvdate}  
*Padlox Escape Rooms, Edinburgh* 

**Verwaltungsassistent**[*06/2021 --- 08/2021*]{.cvdate}  
*Covid-19 Impfzentrum -- Arbeitsgemeinschaft Notfallmedizin Fürth e. V.* 

**Logistikassistent**[*07/2020 --- 09/2020*]{.cvdate}  
*IKEA Deutschland, Fürth* 

**Küchenhilfe -- Michelin-Stern Restaurant**[*03/2020 --- 04/2020*]{.cvdate}  
*„L’impertinent“ Biarritz, Frankreich* -- Rückkehr nach Deutschland aufgrund von Covid-19 

**Verkäufer im Einzelhandel**[*05/2017 --- 09/2017*]{.cvdate}  
*E-Center EDEKA Schuler, Fürth* 

**Praktikant bei Radiosender -- “Hit Radio N1”**[*07/2015*]{.cvdate}  
*Funkhaus Nürnberg*  


::: {.print-only style="margin-top: 2em;"}
  
**Referenzen**  
Auf Anfrage erhältlich
:::
:::


